platform :ios, '12.0'
use_frameworks!

target 'EsamDScrollView_Example' do
  pod 'TinyConstraints', '~> 4.0.0'
  pod 'EsamDScrollView', :path => '../'

  target 'EsamDScrollView_Tests' do
    inherit! :search_paths

    
  end
end
